import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import { Providers } from "./providers";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, minimum-scale=1"
        />
        <link
          rel="shortcut icon"
          href="assets/images/logo5.png"
          type="image/x-icon"
        />
        <meta
          name="description"
          content="Узнай, кто из твоих друзей уже нашел свою половинку в онлайн-знакомствах!"
        />

        <Script id="ya-metrika">{`
        (function(m, e, t, r, i, k, a) {
            m[i] = m[i] || function() {
                (m[i].a = m[i].a || []).push(arguments)
            };
            m[i].l = 1 * new Date();
            for (var j = 0; j < document.scripts.length; j++) {
                if (document.scripts[j].src === r) {
                    return;
                }
            }
            k = e.createElement(t), a = e.getElementsByTagName(t)[0], k.async = 1, k.src = r, a.parentNode.insertBefore(k, a)
        })
        (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

        ym(96804458, "init", {
            clickmap: true,
            trackLinks: true,
            accurateTrackBounce: true,
            webvisor: true
        });
        `}</Script>

        <title>Онлайн-знакомства проверка</title>
        <link
          rel="stylesheet"
          href="assets/web/assets/mobirise-icons2/mobirise2.css"
        />
        <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css" />
        <link
          rel="stylesheet"
          href="assets/bootstrap/css/bootstrap-grid.min.css"
        />
        <link
          rel="stylesheet"
          href="assets/bootstrap/css/bootstrap-reboot.min.css"
        />
        <link rel="stylesheet" href="assets/parallax/jarallax.css" />
        <link rel="stylesheet" href="assets/socicon/css/styles.css" />
        <link rel="stylesheet" href="assets/theme/css/style.css" />
        <link
          rel="preload"
          as="style"
          href="assets/mobirise/css/mbr-additional.css?v=x7Wl7U"
        />
        <link
          rel="stylesheet"
          href="assets/mobirise/css/mbr-additional.css?v=x7Wl7U"
          type="text/css"
        />
        <link rel="stylesheet" href="assets/form_send_photos.css" />

        <noscript>
          <div>
            <img
              src="https://mc.yandex.ru/watch/96804458"
              style={{ position: "absolute", left: "-9999px" }}
              alt=""
            />
          </div>
        </noscript>
      </head>
      <body className={inter.className}>
        <Theme>
          <Providers>{children}</Providers>
        </Theme>
      </body>
    </html>
  );
}
